### ISSUE TITLE
`attach_function': Function 'getdtablesize' not found in [libc.so] (FFI::NotFoundError)

### ISSUE THREAD

**Issue by binrusdi** [rack/rackup#11]
I tried running rackup on termux, but it returned a message about FFI.

`/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/ffi-1.15.5/lib/ffi/library.rb:273:in `attach_function': Function 'getdtablesize' not found in [libc.so] (FFI::NotFoundError)                         from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/ethon-0.16.0/lib/ethon/libc.rb:17:in `<module:Libc>'                  from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/ethon-0.16.0/lib/ethon/libc.rb:7:in `<module:Ethon>'                  from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/ethon-0.16.0/lib/ethon/libc.rb:2:in `<top (required)>'                from <internal:/data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'                  from <internal:/data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'                  from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/ethon-0.16.0/lib/ethon.rb:15:in `<top (required)>'                    from <internal:/data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'                  from <internal:/data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'                  from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'                from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/runtime.rb:60:in `require'                  from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/runtime.rb:60:in `block (2 levels) in require'                                                                from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/runtime.rb:55:in `each'                     from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/runtime.rb:55:in `block in require'         from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/runtime.rb:44:in `each'                     from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler/runtime.rb:44:in `require'                  from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/bundler-2.4.6/lib/bundler.rb:195:in `require'                         from /data/data/com.termux/files/home/devdocs/lib/docs.rb:2:in `<top (required)>'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /data/data/com.termux/files/home/devdocs/lib/app.rb:38:in `block in <class:App>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:1551:in `configure'
        from /data/data/com.termux/files/home/devdocs/lib/app.rb:14:in `<class:App>'
        from /data/data/com.termux/files/home/devdocs/lib/app.rb:6:in `<top (required)>'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /data/data/com.termux/files/home/devdocs/config.ru:5:in `block in <main>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/rack-2.2.8/lib/rack/builder.rb:116:in `eval'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/rack-2.2.8/lib/rack/builder.rb:116:in `new_from_string'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/rack-2.2.8/lib/rack/builder.rb:105:in `load_file'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/rack-2.2.8/lib/rack/builder.rb:66:in `parse_file'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/rack-2.2.8/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/rack-2.2.8/lib/rack/server.rb:249:in `app'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/rack-2.2.8/lib/rack/server.rb:422:in `wrapped_app'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/rack-2.2.8/lib/rack/server.rb:312:in `block in start'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/rack-2.2.8/lib/rack/server.rb:379:in `handle_profiling'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/rack-2.2.8/lib/rack/server.rb:311:in `start'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/rack-2.2.8/lib/rack/server.rb:168:in `start'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/rack-2.2.8/bin/rackup:5:in `<top (required)>'
        from /data/data/com.termux/files/usr/bin/rackup:25:in `load'
        from /data/data/com.termux/files/usr/bin/rackup:25:in `<main>'`

**Comment by ioquatix** [comment]
This error does not look related to `rackup` but perhaps `ethon`.
